### ISSUE TITLE
SBT Native Compilation on Mac

### ISSUE THREAD

**Issue by joesan** [jodersky/flow#39]
I guess I had similar problems earlier, but I did not continue solving it the last time and I'm now in the process of using flow for one of my projects and I just checked out the source code and followed the documentation

http://www.jodersky.ch/flow/documentation/3.0/developer - Creating a fat jar

I get the following error:

jothi@Joesans-MacBook-Pro ~/P/P/flow> sbt native/package
[info] Loading project definition from /Users/jothi/Projects/Personal/flow/project
[info] Set current project to root (in build file:/Users/jothi/Projects/Personal/flow/)
[info] Building library with native build tool CMake
Exception in thread "Thread-9" java.io.IOException: Cannot run program "cmake" (in directory "/Users/jothi/Projects/Personal/flow/flow-native/target/native/x86_64-darwin/build"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.SequentialProcess.runAndExitValue(ProcessImpl.scala:240)
	at sbt.CompoundProcess$$anonfun$1.apply$mcV$sp(ProcessImpl.scala:201)
	at sbt.Spawn$$anon$3.run(ProcessImpl.scala:17)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
Exception in thread "Thread-8" java.lang.RuntimeException: No exit code: process destroyed.
	at scala.sys.package$.error(package.scala:27)
	at sbt.CompoundProcess$$anonfun$exitValue$1.apply(ProcessImpl.scala:193)
	at sbt.CompoundProcess$$anonfun$exitValue$1.apply(ProcessImpl.scala:193)
	at scala.Option.getOrElse(Option.scala:120)
	at sbt.CompoundProcess.exitValue(ProcessImpl.scala:193)
	at sbt.SequentialProcess$$anonfun$runAndExitValue$1.apply$mcI$sp(ProcessImpl.scala:241)
	at sbt.SequentialProcess$$anonfun$runAndExitValue$1.apply(ProcessImpl.scala:241)
	at sbt.SequentialProcess$$anonfun$runAndExitValue$1.apply(ProcessImpl.scala:241)
	at sbt.CompoundProcess.runInterruptible(ProcessImpl.scala:214)
	at sbt.SequentialProcess.runAndExitValue(ProcessImpl.scala:241)
	at sbt.CompoundProcess$$anonfun$1.apply$mcV$sp(ProcessImpl.scala:201)
	at sbt.Spawn$$anon$3.run(ProcessImpl.scala:17)

I guess that I need to have Make installed on my Mac?

Any ideas?

**Comment by jodersky** [comment]
CMake is required to build the native library. Basically, running `sbt native/package` will perform all steps described [here](https://github.com/jodersky/flow/blob/master/Documentation/developer.md#build-process) and thus requires the same dependencies.
